"""Approval request data model.

Stores approval requests generated when high-risk operations are detected,
tracking the full lifecycle from creation through decision or timeout.
"""

import datetime
import enum

from sqlalchemy import (
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)

from skyvern.forge.sdk.db.models import Base
from skyvern.forge.sdk.db.id import generate_id


class ApprovalStatus(str, enum.Enum):
    """Lifecycle states for an approval request."""

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    TIMEOUT = "timeout"


APPROVAL_PREFIX = "apr"


def generate_approval_id() -> str:
    return f"{APPROVAL_PREFIX}_{generate_id()}"


# Default timeout in seconds per risk level
DEFAULT_TIMEOUTS = {
    "high": 3600,       # 1 hour
    "critical": 1800,   # 30 minutes (critical = more urgent)
}


class ApprovalRequestModel(Base):
    """Approval request generated by the risk detection engine."""

    __tablename__ = "approval_requests"

    approval_id = Column(String, primary_key=True, default=generate_approval_id)
    task_id = Column(String, nullable=False, index=True)
    organization_id = Column(
        String,
        ForeignKey("organizations.organization_id"),
        nullable=False,
        index=True,
    )
    department_id = Column(
        String,
        ForeignKey("departments.department_id"),
        nullable=False,
        index=True,
    )
    business_line_id = Column(
        String,
        ForeignKey("business_lines.business_line_id"),
        nullable=True,
    )
    # Identity snapshot used to enforce separation of duties at decision time.
    requester_user_id = Column(String, nullable=True, index=True)

    # Risk assessment details
    risk_level = Column(String, nullable=False)
    risk_reason = Column(Text, nullable=False)
    operation_description = Column(Text, nullable=True)
    screenshot_path = Column(String, nullable=True)

    # Approval routing
    approver_department_id = Column(String, nullable=False)
    approver_role = Column(String, default="approver", nullable=False)
    notify_department_ids = Column(String, nullable=True)  # comma-separated

    # Lifecycle
    status = Column(String, default=ApprovalStatus.PENDING.value, nullable=False)
    requested_at = Column(
        DateTime, default=datetime.datetime.utcnow, nullable=False, index=True
    )
    approver_user_id = Column(String, nullable=True)
    decided_at = Column(DateTime, nullable=True)
    decision_note = Column(Text, nullable=True)
    timeout_seconds = Column(Integer, default=3600, nullable=False)

    __table_args__ = (
        Index("idx_apr_org_status", "organization_id", "status"),
        Index("idx_apr_dept_status", "approver_department_id", "status"),
        CheckConstraint(
            f"status IN ('{ApprovalStatus.PENDING.value}', "
            f"'{ApprovalStatus.APPROVED.value}', "
            f"'{ApprovalStatus.REJECTED.value}', "
            f"'{ApprovalStatus.TIMEOUT.value}')",
            name="ck_valid_approval_status",
        ),
        CheckConstraint(
            "timeout_seconds > 0",
            name="ck_positive_timeout",
        ),
    )
